LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
  Enabled: true

MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Max: 23
  Enabled: true

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false
