LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120
  Enabled: true

MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Max: 23
  Enabled: true

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: leading
  # EnforcedStyle: trailing
  Enabled: true

StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Max: 8

ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  CountComments: false  # count full line comments?
  Max: 330
